### ISSUE TITLE
포켓몬 분류와 특성의 한글 표기

### ISSUE THREAD

**Issue by kspvillain** [yf-dev/pokemantle#10]
유사도 계산때문에 한글로 표기가 힘든건가요?
name.csv처럼 영문명,한글명으로 정리된 자료가 있으면 한글 표기 가능한가요?

**Comment by rishubil** [comment]
유사도 계산때문에 그런건 아니고, 정리된 자료가 없어서 한글로 표시하지 않고 있습니다. 정리된 데이터가 있으면 표시 가능합니다.

**Comment by kspvillain** [comment]
[pokedex.csv](https://github.com/yf-dev/pokemantle/files/8686657/pokedex.csv)

901 Ursaluna 의 ability_1
Gut -> Guts

[name_map_ability.csv](https://github.com/yf-dev/pokemantle/files/8686735/name_map_ability.csv)

8세대 SwSh까지의 특성 이름 정리 (PLA는 새로운 특성 없음)

포켓몬 분류는 출처마다 다른 내용이 있어서 검증이 필요할거같습니다
