### ISSUE TITLE
이틀연속 같은 포켓몬

### ISSUE THREAD

**Issue by gw040708** [yf-dev/pokemantle#11]
어제와 정답이 같은데 오류인가요 아니면 정상인가요

**Comment by rishubil** [comment]
15번째 정답까지는 별도로 생성한 목록 순서대로 정답을 정해놓았지만, 16번째부터는 랜덤하게 선택된 포켓몬이 정답으로 지정됩니다. 아마도 우연히 15번째 정답과 16번째 정답이 동일했던 것 같습니다.

혹시라도 다음에 비슷한 문제가 발생할 수 있으므로, old_secret 파일을 갱신할 때에는 강제로 시드를 변경하도록 하겠습니다.
