### ISSUE TITLE
디아루가 오리진 폼, 펄기아 오리진 폼의 is_hisuian=1 수정

### ISSUE THREAD

**Issue by kspvillain** [yf-dev/pokemantle#17]
[pokedex.csv](https://github.com/yf-dev/pokemantle/files/8756180/pokedex.csv)

483,Dialga Origin Forme,,,,0 -> 1
484 Palkia Origin Forme,,,,0 -> 1

#16 적용되지 않은 버전입니다

**Comment by rishubil** [comment]
해당 항목이 히스이의 모습이 맞나요?
폼 체인지로 봐야하지 않을까요?

**Comment by kspvillain** [comment]
폼 체인지가 맞는거같습니다
https://pokemonkorea.co.kr/legends_arceus/menu138
에서도 "히스이의 모습"과 "오리진폼"은 별개로 보고 있네요

**Comment by rishubil** [comment]
변경해야 할 사항이 없으므로 이슈를 닫습니다.
