### ISSUE TITLE
9세대 포켓몬 추가

### ISSUE THREAD

**Issue by kspvillain** [yf-dev/pokemantle#18]
[pokedex.csv](https://github.com/yf-dev/pokemantle/files/10251900/pokedex.csv)
[name_map.csv](https://github.com/yf-dev/pokemantle/files/10251902/name_map.csv)

1. 9세대 포켓몬 추가
  전국도감 번호는 아직 포켓몬 홈 연동이 없어 공식적이진 않으나
  [bulbapedia](https://bulbapedia.bulbagarden.net/)의 정리 순서를 대부분 인용하고 있습니다 
2. is_paldean 열 추가
  팔데아 리전폼 켄타로스, 우파 4종
3. is_gigantamax 열 추가
  기록은 했으나 사용하지 않고 날리셔도 됩니다
4. has_forme_difference, is_forme_change 명확하게 정리
  [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_form_differences)의 설명에 따라 리전폼, 성별 차이, 메가진화, 거다이맥스, 기타 "도감에 기록되는 " 다른 모습을 가지고 있으면
   has_forme_difference=1
  게임상에서 모습을 변환시킬 수 있는 기믹이 존재하는 경우 is_forme_change=1
5. 8세대 출신 포켓몬들의 base_friendship, base_experience 비어있는 항목 채워넣음
   PLA(레알세) 출신 포켓몬들은 여전히 데이터가 없어서 비어있습니다

질문
1. 1133 1134 행의 925 Maushold 의 네마리폼, 세마리폼
    1202 1203 행의 982 Dudunsparce 의 두마디폼, 세마디폼
  능력은 완전 동일하나 도감상 구분이 되어있고 키, 몸무게가 다릅니다
  이건 분류를 나눠야할까요?

2. 1179-1184 행의 966 Revavroom
  게임상 스타단의 스타모빌이라고 해서 보스전 NPC전용으로만 등장하는 개체가 있습니다
  타입과 특성이 다른것까지는 확인되었는데 그 이상의 자료가 없습니다

3. 새로 추가된 특성의 번역은 어떤 파일을 건드려야 하는건가요?

**Comment by rishubil** [comment]
720e844 에서 작업해주신 내용을 반영했습니다.

그리고 질문해주신 내용에 대한 내용에 대해서는,

1. 키/몸무게도 유사도 추정에 사용되므로 나누는게 맞다고 생각합니다.
2. 스타모빌은 지금으로서 필요한 필수 정보가 부족해서 넣을 수 없지만, 언젠가 정보가 생기면 추가해야 할 것 같습니다.
3. 신규 특성의 경우 `/frontend/i18n` 디렉터리에 있는 파일들에 추가해야 합니다. 추가하는 방법은 720e844 커밋 내용을 참고하시면 됩니다. (이번에는 제가 추가해뒀습니다.)
