### ISSUE TITLE
9세대 포켓몬 이름 오타 수정

### ISSUE THREAD

**Issue by kspvillain** [yf-dev/pokemantle#19]
[name_map.csv](https://github.com/yf-dev/pokemantle/files/10304138/name_map.csv)

old - new
파퓨돈(암컷) - 퍼퓨돈(암컷)
트레피더 - 트래피더
시비꼬(옐로우 페더) - 시비꼬(옐로 페더)
스테솔트 - 스태솔트
찌리베리 - 찌리배리
마스티프 - 마피티프
졀벼게 - 절벼게
클레스파트라 - 클레스퍼트라

검수용 자료 출처 : 포켓몬스터 바이올렛 버전 실제 게임내 도감

**Comment by rishubil** [comment]
56eff02 에서 적용했습니다.
