### ISSUE TITLE
Clicking autocomplete offer on Safari doesn't work

### ISSUE THREAD

**Issue by RieLCho** [yf-dev/pokemantle#21]
I've tested on MacBook Pro 2020 m1 13' and iPhone mini 12 and clicking (touching) the offer that input shows me doesn't work (autocomplete for me) at all. On my windows desktop & macOS chrome & macOS firefox, it works! so I think this is a bug.

<img width="396" alt="스크린샷 2023-04-11 오전 10 24 35" src="https://user-images.githubusercontent.com/13748138/231031114-39ccb78f-6303-4ba1-bb21-7d8cd58139cd.png">

**Comment by rishubil** [comment]
I have checked the issues and PR.
But recently, I have been a bit short on time due to other tasks, so it may take me a little longer to review and merge the PR.

Thank you!

**Comment by rishubil** [comment]
Fixed in 8a6a15794dcce9d2eedd36ebad64754e3e6e936d.
