### ISSUE TITLE
히스이도감 추가+문제점

### ISSUE THREAD

**Issue by kspvillain** [yf-dev/pokemantle#8]
1. 히스이 리전 폼 리스트 추가
is_hisuian 열 추가했습니다
히스이 리전폼 17종 추가, 진화체 10종 추가

2. is_9th 열 만들어도 되나요?

3. 일부 히스이 한정 포켓몬들의 포획률, 알 걸음수 데이터 없음

[name_map.csv](https://github.com/yf-dev/pokemantle/files/8598777/name_map.csv)
[pokedex.csv](https://github.com/yf-dev/pokemantle/files/8598778/pokedex.csv)

**Comment by rishubil** [comment]
`is_9th`가 9세대 포켓몬을 의미한다면,  `generation`에 9로 표시할 수 있습니다.
그리고 포획률과 알 걸음수는 데이터가 없다면 빈칸으로 두셔도 됩니다.
