### ISSUE TITLE
자시안 자마젠타의 폼 한글명이 바뀌어 있습니다

### ISSUE THREAD

**Issue by kspvillain** [yf-dev/pokemantle#9]
old

> Zacian Crowned Sword,자시안
> Zacian Hero of Many Battles,자시안(검왕)
> Zamazenta Crowned Shield,자마젠타
> Zamazenta Hero of Many Battles,자마젠타(방패왕)

new

> Zacian Crowned Sword,자시안(검왕)
> Zacian Hero of Many Battles,자시안
> Zamazenta Crowned Shield,자마젠타(방패왕)
> Zamazenta Hero of Many Battles,자마젠타

가 되어야 합니다

[name_map.csv](https://github.com/yf-dev/pokemantle/files/8642210/name_map.csv)

**Comment by rishubil** [comment]
32b8facaf3e8f123c0e1ddba04f3c2b987cfd340 에서 적용됨
